apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-nginx
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: nginx
      targetRevision: "18.1.0"
      helm:
        valueFiles:
          - $values/02-cloud-native-tooling/argocd/apps/hello/values.yaml
    - repoURL: https://github.com/dfoguedes/lab
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: hello
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
